import html
import json
from datetime import datetime, timezone


def make_case_id(timestamp=None):
    timestamp = timestamp or datetime.now(timezone.utc)
    return timestamp.strftime("PS-%Y%m%d-%H%M%S-%f")[:-3]


def make_report_payload(
    case_id, quality, measures, outcome, settings, language="English"
):
    safety_notice = (
        "यह शोध प्रोटोटाइप बीमारी का निदान नहीं करता और योग्य स्वास्थ्य पेशेवर "
        "द्वारा जांच का स्थान नहीं ले सकता।"
        if language == "Hindi"
        else (
            "This research prototype does not diagnose disease and must not replace "
            "an examination by a qualified healthcare professional."
        )
    )
    return {
        "case_id": case_id,
        "created_at": datetime.now(timezone.utc).isoformat(),
        "intended_use": "Research decision support for retinal vessel mapping",
        "diagnosis": None,
        "diagnosis_message": "No diagnosis was generated by ProbStrip.",
        "quality": quality.to_dict(),
        "research_measures": measures,
        "review_outcome": outcome,
        "model_settings": settings,
        "patient_language": language,
        "safety_notice": safety_notice,
    }


def report_as_json(payload):
    return json.dumps(payload, indent=2)


def report_as_html(payload):
    quality = payload["quality"]
    measures = payload["research_measures"]
    outcome = payload["review_outcome"]
    checks = "".join(
        "<tr><td>{}</td><td>{:.1f} {}</td><td>{}</td></tr>".format(
            html.escape(check["name"]),
            check["value"],
            html.escape(check["unit"]),
            html.escape(check["status"]),
        )
        for check in quality["checks"]
    )
    language = payload.get("patient_language", "English")
    if language == "Hindi":
        strings = {
            "title": "ProbStrip रेटिना रक्त वाहिका रिपोर्ट",
            "no_diagnosis": "कोई निदान तैयार नहीं किया गया।",
            "your_result": "आपका परिणाम",
            "next_step": "अब क्या करें",
            "quality": "तस्वीर की गुणवत्ता",
            "score": "स्कोर",
            "research": "अनुसंधान माप",
            "coverage": "दिखाई देने वाली रक्त वाहिका कवरेज",
            "uncertainty": "कम विश्वास वाला क्षेत्र",
            "measurement_note": (
                "ये माप सॉफ्टवेयर के परिणाम का वर्णन करते हैं, आपके स्वास्थ्य या बीमारी का नहीं।"
            ),
        }
    else:
        strings = {
            "title": "ProbStrip retinal vessel report",
            "no_diagnosis": "No diagnosis was generated.",
            "your_result": "Your result",
            "next_step": "Next step",
            "quality": "Image quality",
            "score": "Score",
            "research": "Research measurements",
            "coverage": "Visible vessel coverage",
            "uncertainty": "Low-confidence area",
            "measurement_note": (
                "These measurements describe the software output, not your health and not the presence or absence of disease."
            ),
        }
    return f"""<!doctype html>
<html lang="en"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width">
<title>ProbStrip report {html.escape(payload['case_id'])}</title>
<style>body{{font-family:Arial,sans-serif;max-width:760px;margin:32px auto;padding:0 20px;color:#17202a;line-height:1.55}}h1{{font-size:26px}}h2{{font-size:18px;margin-top:28px}}.notice{{border-left:5px solid #d97706;background:#fff7ed;padding:14px}}table{{border-collapse:collapse;width:100%}}td,th{{border-bottom:1px solid #d8dee4;padding:9px;text-align:left}}.result{{background:#ecfdf5;padding:16px;border-radius:6px}}small{{color:#52606d}}</style></head>
<body><h1>{strings['title']}</h1><small>Reference: {html.escape(payload['case_id'])}</small>
<div class="notice"><strong>{strings['no_diagnosis']}</strong><br>{html.escape(payload['safety_notice'])}</div>
<h2>{strings['your_result']}</h2><div class="result"><strong>{html.escape(outcome['title'])}</strong><p>{html.escape(outcome['explanation'])}</p><p><strong>{strings['next_step']}:</strong> {html.escape(outcome['next_step'])}</p></div>
<h2>{strings['quality']}</h2><p>{strings['score']}: {quality['score']}/100. {html.escape(quality['summary'])}</p>
<table><thead><tr><th>Check</th><th>Value</th><th>Status</th></tr></thead><tbody>{checks}</tbody></table>
<h2>{strings['research']}</h2><p>{strings['coverage']}: {measures['visible_vessel_coverage_percent']:.2f}%<br>{strings['uncertainty']}: {measures['low_confidence_area_percent']:.2f}%</p>
<p><small>{strings['measurement_note']}</small></p></body></html>"""


def report_as_fhir(payload):
    """Create a minimal research-only FHIR DiagnosticReport-shaped export."""
    return json.dumps(
        {
            "resourceType": "DiagnosticReport",
            "id": payload["case_id"].lower(),
            "status": "preliminary",
            "category": [{"text": "Research retinal image analysis"}],
            "code": {"text": "Retinal vessel mapping (research use only)"},
            "effectiveDateTime": payload["created_at"],
            "conclusion": payload["diagnosis_message"],
            "note": [{"text": payload["safety_notice"]}],
            "result": [{"reference": "#visible-vessel-coverage"}],
            "contained": [
                {
                    "resourceType": "Observation",
                    "id": "visible-vessel-coverage",
                    "status": "preliminary",
                    "code": {"text": "Visible vessel coverage"},
                    "valueQuantity": {
                        "value": payload["research_measures"][
                            "visible_vessel_coverage_percent"
                        ],
                        "unit": "%",
                    },
                }
            ],
        },
        indent=2,
    )
